### ISSUE TITLE
Ticking the checkbox to automatically set the timezone during installation crashes FreeBSD Installer app

### ISSUE THREAD

**Issue by schusz** [helloSystem/hello#165]

**Comment by probonopd** [comment]
Thanks @schusz. Could you run the installer from the command line and see whether you get any backtrace/error messages there?

**Comment by schusz** [comment]
@probonopd  I could not find how to start the 'Install FreeBSD.app' from the command line.
I dragged the app icon into a shell window and pressed enter. That started the app.
This is probably not what you meant. So please tell me how to start the app from the command line.

In the mean time I can tell you that when I tick the checkbox and click 'Yes', the app crashes.
When I tick the checkbox and click 'No', the checkbox remain ticked.
But it doesn't seem to have any effect on the timezone setting, because the system time still does not reflect the actaul time (CET+ 1; summer time) when the installed system has rebooted.

**Comment by probonopd** [comment]
Please run in a QTerminal window (you can copy and paste this):
```
/Applications/Utilities/Install\ FreeBSD.app/Install\ FreeBSD
```

Then you should see output on the command line when the crash happens. Can you please copy & paste this here?

I suspect there is a bug which I cannot reproduce because it may happen only under certain circumstances.

**Comment by schusz** [comment]
@probonopd  Output of `/Applications/Utilities/Install\ FreeBSD.app/Install\ FreeBSD`:

`Preparing wizard
Pre-existing /tmp/Installer.log removed
Pre-existing /tmp/Installer.err removed
UTF-8 locales supported by the system:
['af_ZA', 'am_ET', 'ar_AE', 'ar_EG', 'ar_JO', 'ar_MA', 'ar_QA', 'ar_SA', 'be_BY', 'bg_BG', 'ca_AD', 'ca_ES', 'ca_FR', 'ca_IT', 'cs_CZ', 'da_DK', 'de_AT', 'de_CH', 'de_DE', 'el_GR', 'en_AU', 'en_CA', 'en_GB', 'en_HK', 'en_IE', 'en_NZ', 'en_PH', 'en_SG', 'en_US', 'en_ZA', 'es_AR', 'es_CR', 'es_ES', 'es_MX', 'et_EE', 'eu_ES', 'fi_FI', 'fr_BE', 'fr_CA', 'fr_CH', 'fr_FR', 'ga_IE', 'he_IL', 'hi_IN', 'hr_HR', 'hu_HU', 'hy_AM', 'is_IS', 'it_CH', 'it_IT', 'ja_JP', 'kk_KZ', 'ko_KR', 'lt_LT', 'lv_LV', 'mn_MN', 'nb_NO', 'nl_BE', 'nl_NL', 'nn_NO', 'pl_PL', 'pt_BR', 'pt_PT', 'ro_RO', 'ru_RU', 'se_FI', 'se_NO', 'sk_SK', 'sl_SI', 'sr_RS', 'sv_FI', 'sv_SE', 'tr_TR', 'uk_UA', 'zh_CN', 'zh_HK', 'zh_TW']
Languages supported by the system:
['af', 'de', 'ca', 'cs', 'en', 'fi', 'kk', 'ro', 'pt', 'it', 'mn', 'be', 'sv', 'hr', 'et', 'ar', 'am', 'he', 'nb', 'lt', 'eu', 'ga', 'lv', 'nn', 'es', 'se', 'sk', 'pl', 'ru', 'sr', 'sl', 'nl', 'uk', 'bg', 'hy', 'hu', 'zh', 'ja', 'ko', 'da', 'tr', 'fr', 'hi', 'el', 'is']
Keyboard layouts supported by the system:
['af', 'al', 'altwin', 'am', 'apl', 'ara', 'at', 'au', 'az', 'ba', 'bd', 'be', 'bg', 'br', 'brai', 'bt', 'bw', 'by', 'ca', 'capslock', 'cd', 'ch', 'cm', 'cn', 'compose', 'ctrl', 'cz', 'de', 'dk', 'dz', 'ee', 'eg', 'empty', 'epo', 'es', 'et', 'eu', 'eurosign', 'fi', 'fo', 'fr', 'gb', 'ge', 'gh', 'gn', 'gr', 'group', 'hr', 'hu', 'id', 'ie', 'il', 'in', 'inet', 'iq', 'ir', 'is', 'it', 'jp', 'jv', 'ke', 'keypad', 'kg', 'kh', 'kpdl', 'kr', 'kz', 'la', 'latam', 'latin', 'level2', 'level3', 'level5', 'lk', 'lt', 'lv', 'ma', 'mao', 'md', 'me', 'mk', 'ml', 'mm', 'mn', 'mt', 'mv', 'my', 'nbsp', 'ng', 'nl', 'no', 'np', 'olpc', 'parens', 'pc', 'ph', 'pk', 'pl', 'pt', 'ro', 'rs', 'ru', 'rupeesign', 'se', 'shift', 'si', 'sk', 'sn', 'srvr_ctrl', 'sy', 'terminate', 'tg', 'th', 'tj', 'tm', 'tr', 'trans', 'tw', 'typo', 'tz', 'ua', 'us', 'uz', 'vn', 'za']
Preparing IntroPage
Preparing LicensePage
Preparing DiskPage
Preparing UserPage
QLayout: Attempting to add QLayout "" to UserPage "", which already has a layout
Starting kenv ['-q', 'smbios.system.product']
Preparing InstallationPage
Preparing SuccessPage
Displaying DiskPage
Starting sudo ['-n', '-E', 'furybsd-install']
b'INSTALLER_MIB_NEEDED=1010'
Response from the installer script: 1010
Adjusted MiB needed: 1515
periodically_list_disks
Running command: /sbin/geom disk status -s
Running command: /sbin/geom disk list cd0
Running command: /sbin/geom disk list ada0
Running command: /sbin/geom disk list da0
Running command: /sbin/geom disk list cd0
Running command: /sbin/geom disk list ada0
Running command: /sbin/geom disk list da0
Disk space required: 1515 MiB
Running command: /sbin/geom disk status -s
Running command: /sbin/geom disk list cd0
Running command: /sbin/geom disk list ada0
Running command: /sbin/geom disk list da0
User has agreed to erase all contents of this disk
Running command: /sbin/geom disk status -s
Running command: /sbin/geom disk list cd0
Running command: /sbin/geom disk list ada0
Running command: /sbin/geom disk list da0
Running command: /sbin/geom disk list cd0
 on cd0 
Running command: /sbin/geom disk list ada0
 on ada0 
Running command: /sbin/geom disk status -s
Running command: /sbin/geom disk list cd0
Running command: /sbin/geom disk list ada0
Running command: /sbin/geom disk list da0
Running command: /sbin/geom disk list cd0
 on cd0 
Running command: /sbin/geom disk list ada0
 on ada0 
Running command: /sbin/geom disk status -s
Running command: /sbin/geom disk list cd0
Running command: /sbin/geom disk list ada0
Running command: /sbin/geom disk list da0
Running command: /sbin/geom disk list cd0
 on cd0 
Running command: /sbin/geom disk list ada0
 on ada0 
Displaying UserPage
self.computer_name: Latitude-E4300
User has agreed to geolocate
Geolocating using https://ipapi.co/json/
Traceback (most recent call last):
  File "/Applications/Utilities/Install FreeBSD.app/Resources/freebsd-install.py", line 240, in _geolocate
    if os.path.exists("/usr/share/zoneinfo/" + data["timezone"]):
TypeError: can only concatenate str (not "NoneType") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Utilities/Install FreeBSD.app/Resources/freebsd-install.py", line 960, in setTimezone
    wizard.ask_user_to_geolocate()
  File "/Applications/Utilities/Install FreeBSD.app/Resources/freebsd-install.py", line 264, in ask_user_to_geolocate
    self._geolocate()
  File "/Applications/Utilities/Install FreeBSD.app/Resources/freebsd-install.py", line 243, in _geolocate
    except urllib.error as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
zsh: abort      /Applications/Utilities/Install\ FreeBSD.app/Install\ FreeBSD`

**Comment by probonopd** [comment]
It seems that `data["timezone"]` is None in your case, which leads to the crash. I need to investigate why this happpens. Does https://ipapi.co/json/ return the correct values for you?

**Comment by probonopd** [comment]
So we have a `try` statement but the `except` is wrong...

https://github.com/helloSystem/Utilities/blob/590666300e41502278d8bebbe7b38628a2beb5b2/Utilities/Install%20FreeBSD.app/Resources/freebsd-install.py#L236

> catching classes that do not inherit from BaseException is not allowed

Whatever that means...

**Comment by schusz** [comment]
> It seems that `data["timezone"]` is None in your case, which leads to the crash. I need to investigate why this happpens. Does https://ipapi.co/json/ return the correct `timezone` value for you?

{
    "ip": "45.155.157.169",
    "version": "IPv4",
    "city": "Loo",
    "region": "Overijssel",
    "region_code": null,
    "country": "NL",
    "country_name": "Netherlands",
    "country_code": "NL",
    "country_code_iso3": "NLD",
    "country_capital": "Amsterdam",
    "country_tld": ".nl",
    "continent_code": "EU",
    "in_eu": true,
    "postal": null,
    "latitude": null,
    "longitude": null,
    "timezone": null,
    "utc_offset": null,
    "country_calling_code": "+31",
    "currency": "EUR",
    "currency_name": "Euro",
    "languages": "nl-NL,fy-NL",
    "country_area": 41526.0,
    "country_population": 17231017.0,
    "asn": "AS206238",
    "org": "Freedom Internet BV"
}

**Comment by probonopd** [comment]
> "timezone": null

Now that's quite strange, one would assume that it's not _that_ hard for a web service to find out the timezone for the Netherlands...

**Comment by schusz** [comment]
@probonopd Hi, I ran the Live version of hello-0.5.0_0E208-FreeBSD-13.0-amd64.iso. The FreeBSD Installer app did not crash anymore when I checked the "Set time zone based on current location". And it found my location Europe/Amsterdam. But it does not change time, which is 6 hours too early. It's EDT time zone in stead of CEST which it should be.
In the installed version I changed the time to a wrong value with terminal command ```
sudo date 0412131627
``` and then tried to set the correct date and time with ```
sudo ntpdate -v -b nl.pool.ntp.org
```, but that only set the date and time back to the original value in the EDT time zone.
