### ISSUE TITLE
Consider adding preconfigured Matrix client

### ISSUE THREAD

**Issue by probonopd** [helloSystem/hello#66]
Showstopper: `Guest access not allowed` for IRC bridged channels?

```
>>> from matrix_client.client import MatrixClient
>>> client = MatrixClient("http://matrix.org")
>>> token = client.register_
client.register_as_guest(       client.register_with_password(
>>> token = client.register_as_guest()
>>> print(token)
...-...
>>> room = client.join_room("#freenode_#hellosystem:matrix.org")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/matrix-python-sdk/matrix_client/client.py", line 337, in join_room
    response = self.api.join_room(room_id_or_alias)
  File "/tmp/matrix-python-sdk/matrix_client/api.py", line 234, in join_room
    return self._send("POST", path)
  File "/tmp/matrix-python-sdk/matrix_client/api.py", line 749, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 403: {"errcode":"M_FORBIDDEN","error":"Guest access not allowed"}
```

**Comment by probonopd** [comment]
* In Matrix, chat with IRC NickServ to IDENTIFY using the IRC account and then use GROUP to make the Matrix-generated username `...[m]` basically an alias of the real IRC username https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#how-do-i-registeridentify-to-nickserv
* In IRC, set `/msg ChanServ FLAGS #helloSystem ...[m]  +O`
* Now the user is moderator in Matrix and can allow guest users!

**Comment by probonopd** [comment]
Now, which Qt based Matrix client allows using Matrix as a guest?

**Comment by probonopd** [comment]
Just be aware that the privacy implications of this solution are not optimal, but the channel should be regarded a "public space" without any privacy whatsoever anyway.

https://www.privacy-handbuch.de/handbuch_74g.htm
